name: Pull Request Lint

on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']

jobs:
  title:
    name: ticket check
    runs-on: ubuntu-latest

    steps:
      - name: Check for ticket
        uses: neofinancial/ticket-check-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ticketLink: 'https://app.shortcut.com/:org/story/%ticketNumber%'
          ticketPrefix: 'sc-'
          titleRegex: '^(CH|sc)(-?)(?<ticketNumber>\d+)'
          branchRegex: '^(CH|sc)(-?)(?<ticketNumber>\d+)'
          bodyRegex: '(CH|sc)(-?)(?<ticketNumber>\d+)'
          bodyURLRegex: 'https?:\/\/app\.(clubhouse.io|shortcut.com)(\/:org)\/story\/(?<ticketNumber>\d+)'